name: DevSkim PR Scan

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  devskim_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install DevSkim CLI
        run: dotnet tool install --global Microsoft.DevSkim.CLI

      - name: Run DevSkim Scan on Solution
        run: |
          devskim analyze . --exit-code 1
