name: PR Security Scan

on:
  pull_request:
    branches: [ "*" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DevSkim CLI
        run: dotnet tool install --global Microsoft.CST.DevSkim.CLI

      - name: Run DevSkim Security Scan (Save output)
        run: devskim analyze --source-code . -f test --output-file devskim-results.txt -E

      - name: Show DevSkim Results in Summary
        if: failure()
        run: |
          echo "### DevSkim Security Issues Found"
          cat devskim-results.txt
        shell: bash

      - name: Upload DevSkim Results as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devskim-results
          path: devskim-results.txt
