name: PR Security Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-codeql-scan:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Fail if CodeQL found alerts
        uses: actions/github-script@v7
        with:
          script: |
            const repo = process.env.GITHUB_REPOSITORY;
            const [owner, repoName] = repo.split("/");
            const result = await github.rest.codeScanning.listAlertsForRepo({
              owner,
              repo: repoName,
              state: "open"
            });
            if (result.data.length > 0) {
              core.setFailed(`CodeQL found ${result.data.length} security alert(s)!`);
            } else {
              console.log("No CodeQL alerts found.");
            }
